update 0.2

diff --git a/torbuddy-ng b/torbuddy-ng
--- a/torbuddy-ng
+++ b/torbuddy-ng
@@ -13,64 +13,66 @@ DAEMON="/usr/bin/tor"
 CHAINS="/etc/proxychains.conf"
 CONFIGURATION="$(sudo tor --verify-config | grep 'Configuration was valid')"
 
+function control_c {
+echo -e "\n"
+echo -e "[\e[0;33mINFO\e[0m]\e[0;37m\tShutting down tor...\e[0m"
+sudo kill $(pgrep -x tor)
+sleep 0.5
+echo -e "[\e[0;32mOK\e[0m]\e[0;37m\tDone, I'm outta here\e[0m"
+exit $?
+}
+
 # --- script ------------------------------------------------------------------ #
-		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m	To stop the script press CTRL+C\e[0m"
+		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m\tTo stop the script press CTRL+C\e[0m"
 sleep 2
-		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m	Checking if Tor is installed...\e[0m"
+		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m\tChecking if Tor is installed...\e[0m"
 
 if [ -f "$DAEMON" ];
 	then
-		echo -e "[\e[0;32mOK\e[0m]\e[0;37m	Tor is Installed!\e[0m"
-		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m	Checking for clean configuration\e[0m"
+		echo -e "[\e[0;32mOK\e[0m]\e[0;37m\tTor is Installed!\e[0m"
+		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m\tChecking for clean configuration\e[0m"
 
 if [ -z "$CONFIGURATION" ];
 	then
-		echo -e "[\e[30;48;5;1mWARN\e[0m]\e[0;37m	Invalid configuration. Check torrc file. Exiting\e[0m"
+		echo -e "[\e[30;48;5;1mWARN\e[0m]\e[0;37m\tInvalid configuration. Check torrc file. Exiting\e[0m"
 	exit 1
 
 	fi
 
 sleep 1
-		echo -e "[\e[0;32mOK\e[0m]\e[0;37m	Configuration is clean\e[0m"
-		echo -e "[\e[0;32mOK\e[0m]\e[0;37m	Starting TOR...\e[0m"
+		echo -e "[\e[0;32mOK\e[0m]\e[0;37m\tConfiguration is clean\e[0m"
+		echo -e "[\e[0;32mOK\e[0m]\e[0;37m\tStarting TOR...\e[0m"
 		sudo tor --quiet;
 else
-		echo -e "[\e[30;48;5;1mWARN\e[0m]\e[0;37m	Tor isn't installed!\e[0m"
-	        echo -e "[\e[0;33mINFO\e[0m]\e[0;37m	To install: apt-get update, then apt-get install tor\e[0m"
+		echo -e "[\e[30;48;5;1mWARN\e[0m]\e[0;37m\tTor isn't installed!\e[0m"
+	        echo -e "[\e[0;33mINFO\e[0m]\e[0;37m\tTo install: apt-get update, then apt-get install tor\e[0m"
 exit
 fi
-		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m	Checking if proxychains is installed...\e[0m"
+		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m\tChecking if proxychains is installed...\e[0m"
 
 if [ -f "$CHAINS" ];
 	then
-		echo -e "[\e[0;32mOK\e[0m]\e[0;37m	Proxychains is Installed!\e[0m"
+		echo -e "[\e[0;32mOK\e[0m]\e[0;37m\tProxychains is Installed!\e[0m"
 	else
-		echo -e "[\e[30;48;5;1mWARN\e[0m]\e[0;37m	Proxychains isn't installed!\e[0m"
-		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m	To install: apt-get update, then apt-get install proxychains\e[0m"
+		echo -e "[\e[30;48;5;1mWARN\e[0m]\e[0;37m\tProxychains isn't installed!\e[0m"
+		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m\tTo install: apt-get update, then apt-get install proxychains\e[0m"
 exit
 fi
 
 # loop
-		echo -e "[\e[0;32mOK\e[0m]\e[0;37m	Please enter how many seconds you want to grab a new IP:\c\e[0m"
-read TIME
+		echo -e "[\e[0;32mOK\e[0m]\e[0;37m\tPlease enter how many seconds you want to grab a new IP:\c\e[0m"
+trap control_c SIGINT
+	read TIME
 
 if [ "$TIME" -lt "30" ];
 	then
-		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m	Warning: Less than 30 seconds is not suggested!\e[0m"
-		echo -e "[\e[0;32mOK\e[0m]\e[0;37m	Continuing...\e[0m"
+		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m\tWarning: Less than 30 seconds is not suggested!\e[0m"
+		echo -e "[\e[0;32mOK\e[0m]\e[0;37m\tContinuing...\e[0m"
 	else
-		echo -e "[\e[0;32mOK\e[0m]\e[0;37m	Nameserver change every $TIME seconds\e[0m"
-		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m	Ctrl-Z followed by bg to put script to background...\e[0m"
+		echo -e "[\e[0;32mOK\e[0m]\e[0;37m\tNameserver change every $TIME seconds\e[0m"
+		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m\tCtrl-Z followed by bg to put script to background...\e[0m"
 	fi
 
-function control_c {
-echo -e "\n"
-echo -e "[\e[0;33mINFO\e[0m]\e[0;37m	Shutting down tor...\e[0m"
-sudo kill $(pgrep -x tor)
-sleep 0.5
-echo -e "[\e[0;32mOK\e[0m]\e[0;37m	Done, I'm outta here\e[0m"
-exit $?
-}
 # Capture SIGINT (Ctrl-C) and exit
 trap control_c SIGINT
 for (( ; ; ))
@@ -79,6 +81,7 @@ sleep "$TIME"
 sudo kill $(pgrep -x tor)
 sleep 0.5
 sudo tor --quiet
-echo -e "$TIME seconds until next IP change \n"
+echo -e "[\e[0;33mINFO\e[0m]\e[0;37m\t$TIME seconds until next IP change\n\e[0m"
+echo -e ""
 done
 
